{% set name = "xatlas-python" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/xatlas/xatlas-{{ version }}.tar.gz
    sha256: 72f0bc6c42c19252be87e947d9dfe251c8d6c6943fd43e3d173ddc6b1afad693

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - make
    - pip                # [build_platform != target_platform]
    - python             # [build_platform != target_platform]
    - scikit-build-core  # [build_platform != target_platform]
  host:
    - pip
    - python
    - scikit-build-core
  run:
    - python

test:
  imports:
    - xatlas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mworchel/xatlas-python
  summary: Python bindings for xatlas
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
