{% set name = "xatlas-python" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/xatlas/xatlas-{{ version }}.tar.gz
    sha256: bc36b6c7db8fcf1f58f1b5badd8927fdf8eb2b2182e436f07831dc789c9fbf04

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pip                # [build_platform != target_platform]
    - python             # [build_platform != target_platform]
    - scikit-build-core  # [build_platform != target_platform]
  host:
    - pip
    - python
    - scikit-build-core
  run:
    - python

test:
  imports:
    - xatlas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mworchel/xatlas-python
  summary: Python bindings for xatlas
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
